### ISSUE TITLE
Liens erronés rapport HTML entre la vue sommaire et vue page

### ISSUE THREAD

**Issue by aw73** [cnumr/GreenIT-Analysis-cli#13]
Lors de la génération d'un rapport HTML depuis une liste d'URL, il arrive que les liens dans la page global.html ne renvoi pas vers les bonnes pages.

Exemple de rendu erroné : https://ecoindex.angleweb.info/thermes/
La première page (https://www.thermes-aixlesbains.com/reouverture-thermes-de-marlioz/) ne correspond pas au contenu de la page (2.html)

**Comment by jpreisner** [comment]
Bonjour @aw73, peux-tu partager ton fichier url.yaml ainsi que la commande et les options que tu as exécuté ?

**Comment by aw73** [comment]
Bonjour @jpreisner 

Voici le fichier yml :
[url-thermes.zip](https://github.com/cnumr/GreenIT-Analysis-cli/files/7667584/url-thermes.zip)

Et la commande : `greenit analyse url-thermes.yml ./projects/thermes/index.html --format=html`

**Comment by jpreisner** [comment]
cc @jules-delecour-dav, tu peux fermer cette issue étant donné qu'elle a été traitée ?
