### ISSUE TITLE
Readme - instalation Docker

### ISSUE THREAD

**Issue by LGnord** [cnumr/GreenIT-Analysis-cli#25]
Je pense qu'il manque une étape pour l'instalation : la 5ème devrait être 'cd GreenIT-Analysis-cli'. 

Dans l'état actuel, j'ai un message d'erreur :
/Dockerfile: no such file or directory

**Comment by jpreisner** [comment]
C'est implicite mais tu as raison nous pouvons être plus précis. Je corrige ça.
