### ISSUE TITLE
Readme - Exemple yaml non valide

### ISSUE THREAD

**Issue by LGnord** [cnumr/GreenIT-Analysis-cli#26]
J'ai copier/coller l'exemple suivant :
```
- name : 'Collectif GreenIT.fr écoindex'
  url : 'https://collectif.greenit.fr/'
  actions:
    - name : 'Remplir l'email dans le formulaire de contact'
      type : 'text'
      element: '#form_email'
      content: 'john.doe@mail.com'
      timeoutBefore: 1000
```
Ce qui génére une erreur
url_input_file : "/app/input/url.yaml" is not a valid YAML file.

Pour corriger, j'ai supprimer l'apostrophe dans "l'email" (champ name).

**Comment by jpreisner** [comment]
Je pense que tu as 2 solutions pour faire passer un apostrophe : 
1. Remplace en début les apostrophes par des guillemets au tout début et à la toute fin de ton texte. Exemple : `"Remplir l'email dans le formulaire de contact"`.
2. Au niveau de "l'email", tente de mettre 2 apostrophes. Exemple : `'Remplir l''email dans le formulaire de contact'`. (A confirmer je n'ai pas testé)

Dans tous les cas, nous sommes sur une spécificité du format YAML.

**Comment by LGnord** [comment]
De mon coté, j'ai simplement supprimé l'apastrophe.

L'exemple étant dans le readme, je conseil de le corriger. J'ai pris en main le cli en copiant/collant tous les exemples proposés et j'ai surpris d'y trouver des erreurs.

**Comment by jpreisner** [comment]
Merci pour ton retour, je corrige ça.
