### ISSUE TITLE
Un même run produit des logs différents

### ISSUE THREAD

**Issue by LGnord** [cnumr/GreenIT-Analysis-cli#27]
J'ai lancé trois exécutions de la cli avec les mêmes paramètres (fichier url.yaml ci-dessous - issue des exemples du README) et j'ai optenu 3 logs différents (log complet ci-dessous) :

1. Dans le premier l'analyse est à 16%,
2. Dans le deuxième, il y a une erreur - j'ai du tuer le process avec in 'ctrl C',
3. Dans le troisème, l'analyse est à 100% mais le Create HTML report est à 16%

```
# Analyse l'URL collectif.greenit.fr 
- name : 'Collectif GreenIT.fr'
  url : 'https://collectif.greenit.fr/'

# Analyse l'URL collectif.greenit.fr/outils.html en spécifiant une condition d'attente via un sélecteur CSS
# Réalise une capture d'écran de la page
- name : 'Les outils du collectif GreenIT.fr'
  url : 'https://collectif.greenit.fr/outils.html'
  waitForSelector: '#header'
  screenshot: 'screenshots/outils.png'

# Analyse l'URL collectif.greenit.fr/index_en.html en spécifiant une condition d'attente via un XPath
- url : 'https://collectif.greenit.fr/index_en.html'
  waitForXPath: '//section[2]/div/h2'

- name : 'Collectif GreenIT.fr écoindex'
  url : 'https://collectif.greenit.fr/'
  actions:
    - name : 'Remplir l email dans le formulaire de contact'
      type : 'text'
      element: '#form_email'
      content: 'john.doe@mail.com'
      timeoutBefore: 1000
```

```
L:\Documents\GreenIT-Analysis-cli>cd GreenIT-Analysis-cli

L:\Documents\GreenIT-Analysis-cli\GreenIT-Analysis-cli>docker run -it --init --rm --cap-add=SYS_ADMIN  -v L:\Documents\GreenIT-Analysis-cli\input:/app/input -v L:\Documents\GreenIT-Analysis-cli\output:/app/output -e TZ=Europe/Paris --name containerName imagename greenit analyse /app/input/url.yaml /app/output/index.html --format=html
 Analysing                [=======                                 ] 16%     Remaining: 0.0s     Time: 0.0s
 Analysing                [========================================] 100%     Remaining: 0.0s     Time: 3.6s
 Create Global report     [========================================] 100%     Remaining: 0.0s     Time: 0.1s
 Create HTML report       [=======                                 ] 16%     Remaining: 0.0s     Time: 0.0s
L:\Documents\GreenIT-Analysis-cli\GreenIT-Analysis-cli>docker run -it --init --rm --cap-add=SYS_ADMIN  -v L:\Documents\GreenIT-Analysis-cli\input:/app/input -v L:\Documents\GreenIT-Analysis-cli\output:/app/output -e TZ=Europe/Paris --name containerName imagename greenit analyse /app/input/url.yaml /app/output/index.html --format=html
 Analysing                [========================================] 100%     Remaining: 0.0s     Time: 3.6s
ERROR :
 Error: Protocol error: Connection closed. Most likely the page has been closed.
    at Object.exports.assert (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at Page.close (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1198:21)
    at /app/commands/analyse.js:68:49
    at Array.map (<anonymous>)
    at analyse_core (/app/commands/analyse.js:68:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

^C
L:\Documents\GreenIT-Analysis-cli\GreenIT-Analysis-cli>docker run -it --init --rm --cap-add=SYS_ADMIN  -v L:\Documents\GreenIT-Analysis-cli\input:/app/input -v L:\Documents\GreenIT-Analysis-cli\output:/app/output -e TZ=Europe/Paris --name containerName imagename greenit analyse /app/input/url.yaml /app/output/index.html --format=html
 Analysing                [========================================] 100%     Remaining: 0.0s     Time: 3.7s
 Create Global report     [========================================] 100%     Remaining: 0.0s     Time: 0.1s
 Create HTML report       [=======                                 ] 16%     Remaining: 0.0s     Time: 0.0s
L:\Documents\GreenIT-Analysis-cli\GreenIT-Analysis-cli>
```

**Comment by jpreisner** [comment]
Pour l'erreur rencontrée, c'est quelque chose de "normal" malheureusement. On dépend du framework Puppeteer qui provoque aléatoirement ce genre d'erreur. C'est pour cette raison que nous avons mis en place l'option retry qui permet de rejouer l'analyse sur une même page en cas d'erreur. 

Pour les 16% : il faudrait que j'étudie le comportement de l'utilitaire utilisé pour afficher l'avancement.

**Comment by Krakor92** [comment]
J'ai moi aussi eu l'erreur Puppeteer `Error: Protocol error: Connection closed. Most likely the page has been closed.`. Quand je lançais une analyse sur un ou deux sites ça fonctionnait la plupart du temps mais plus j'avais d'url à analyser, moins il était probable que ça arrive au bout.

Je pense avoir réussi à m'en débarasser en commentant les deux premières lignes du `finally` dans le fichier `commands/analyse.js`.

>![Analyse](https://user-images.githubusercontent.com/24924824/159672154-ca0e9a09-58ff-48fb-9486-9d99b627e204.png)

---

En fait l'analyse se fait correctement, les fichiers d'analyse mais c'est au moment du nettoyage que l'erreur se produit 

Quand on survole la méthode `browser.close()` à la ligne 69, il est écrit:
> Closes browser with all the pages (if any were opened). (...)

Donc je suppose que dans ce contexte, les deux lignes au dessus sont superflu et doivent créer un conflit avec `browser.close()`.

**Comment by Krakor92** [comment]
J'ai moi aussi rencontré l'erreur Puppeteer `Error: Protocol error: Connection closed. Most likely the page has been closed.`. Quand je lançais une analyse sur un ou deux sites ça fonctionnait la plupart du temps mais plus j'avais d'url à analyser, moins il était probable que ça arrive au bout de l’exécution.

J'ai réussi à m'en débarrasser en commentant les deux premières lignes du finally dans le fichier `commands/analyse.js`.

![Analyse](https://user-images.githubusercontent.com/24924824/159674872-93b57a12-e7ed-417a-9f2c-e9e157a2fa66.png)

---

En fait l'analyse se fait correctement, les fichiers json dans le dossier `results` sont bien créés mais c'est le nettoyage de Puppeteer qui pose problème. Quand on survole la méthode browser.close() à la ligne 69, il est écrit:

>Closes browser with all the pages (if any were opened). (...)

Donc je suppose que dans ce contexte, les deux lignes au dessus sont superflues et doivent créer un conflit avec `browser.close()`.

**Comment by jpreisner** [comment]
Merci @Krakor92 pour ton analyse. Je te rejoins  : je ne vois pas l'intérêt de ces 2 lignes si derrière on ferme le navigateur qui de lui-même ferme toutes les pages ouvertes : 

```
//close browser
let pages = await browser.pages();
await Promise.all(pages.map(page =>page.close()));
await browser.close()
```

D'autant plus que dans la fonction `analyseURL` du fichier `analysis.js`, la page est fermée après l'analyse, ce qui est la cause je pense des erreurs obtenues : 
```
//launch analyse
result = await page.evaluate(()=>(launchAnalyse()));

page.close();

// ...
```

@jules-delecour-dav : à ta connaissance, y a-t-il une raison de la présence des lignes suivantes ? 
```
//close browser
let pages = await browser.pages();
await Promise.all(pages.map(page =>page.close()));
```

Je serais partant pour supprimer ces lignes et ne garder que cela :  
```
//close browser
await browser.close();
```

**Comment by demeringo** [comment]
Merci pour la remontée de bug et l'analyse. 🙏
Ce `connection close...` me fait penser à un problème que j'ai plusieurs fois rencontré lors d'une exécution en CI... sans comprendre d'ou il venait.
Je vais retester après le merge.

**Comment by jules-delecour-dav** [comment]
@jpreisner Hello, je me demande si ce n'est pas en lien avec l'analyse page par page et le fait que si tu recharges une page tu n'as pas le même résultat d'ecoindex
Du coup on aurait mis ca en place pour s'assurer qu'on relance une analyse complète à chaque fois
Si tu penses que c'est inutile maintenant autant supprimer

**Comment by jpreisner** [comment]
Je viens de faire des tests sur 2-3 pages : avec ou sans, cela ne change pas les résultats. 
Je pense qu'on peut supprimer ces 2 lignes car : 
1. Une page analysée est fermée juste après la fin de l'analyse
2. Le navigateur est fermé lorsque toutes les pages ont été analysées => cela fermera les éventuelles pages qui n'auront pas été fermées entre temps.

Si ça te va je propose une PR.
