### ISSUE TITLE
Export des screenshot depuis docker

### ISSUE THREAD

**Issue by LGnord** [cnumr/GreenIT-Analysis-cli#28]
Je lance le cli avec docker et un exemple du readme
```
# Analyse l'URL collectif.greenit.fr/outils.html en spécifiant une condition d'attente via un sélecteur CSS
# Réalise une capture d'écran de la page
- name : 'Les outils du collectif GreenIT.fr'
  url : 'https://collectif.greenit.fr/outils.html'
  waitForSelector: '#header'
  screenshot: 'screenshots/outils.png'
```
Je ne trouve pas le repertoire 'screenshots'. J'imaginais le trouver en sous-repertoire de 'output'.

**Comment by jpreisner** [comment]
Peux-tu me donner la commande docker build et docker run que tu utilises ? Il te manque probablement un point de montage.

**Comment by LGnord** [comment]
`docker run -it --init --rm --cap-add=SYS_ADMIN  -v L:\Documents\GreenIT-Analysis-cli\input:/app/input -v L:\Documents\GreenIT-Analysis-cli\output:/app/output -e TZ=Europe/Paris --name containerName imagename`

S'il manque un point de montage, il faudrait le mettre dans le README.
