### ISSUE TITLE
Copie d'écran après des actions

### ISSUE THREAD

**Issue by LGnord** [cnumr/GreenIT-Analysis-cli#29]
Je souhaire effectuer des actions (remplir des champs, cliquer...) et effectuer un screenshot du résultat (afin de valider). Toutes mes tentatives me montre le screenshot de la page vide (peut-être que mes actions n'ont pas été effectuées car elles sont erronées). 

Comment faire ?

Merci

**Comment by jpreisner** [comment]
Quand tu dis page vide, tu veux dire que tu vois ta page mais tu as l'impression que tes actions n'ont pas été réalisées ?

Si oui il est fort possible que ça soit tes sélecteurs qui sont mal configurés, et donc que tes actions ne font pas vraiment ce que tu voudrais.

Peux-tu transmettre ton fichier YAML ?

**Comment by LGnord** [comment]
Si j'ai bien compris, la copie d'écran permet de valider que les selecteurs sont bons.

Tant que la copie d'écran montre des champs non remplis, les selecteurs sont incorrects.

**Comment by jpreisner** [comment]
C'est l'intérêt des screenshots effectivement, de pouvoir debuguer une analyse et comprendre pourquoi on a une erreur, pourquoi on a un résultat étonnant, ...

**Comment by PierreRustOrange** [comment]
Bonjour,
j'ai le même type de soucis sur les screenshots : ils sont systématiquement pris avant l'exécution des actions.

Je suis allé voir le fonctionnement dans le code et je pense qu'il s'agit en réalité d'un bug. Dans cli-core/analysis.js#L51
* le screenshot spécifié au niveau de la page est toujours fait avant les actions : ` await takeScreenshot(page, pageInformations.screenshot);`
* les éventuels screenshot spécifié au niveau action sont bien exécuté ensuite, mais la syntaxe semble erronée, on cherche un attribut `screenshot` au niveau de l'object `actions` , alors que c'est objet et un tableau et n'a donc pas cet attribut `takeScreenshot(page, pageInformations.actions.screenshot);`

Si je modifie les lignes 63-64 ainsi, j'obtiens un unique screenshot fait après les actions (qui vient écraser le screenshot pris avant les actions :
```
       // Take screenshot (even if the action fails)
       if (pageInformations.actions && pageInformations.screenshot) {
           await takeScreenshot(page, pageInformations.screenshot);
        }
```
Il serait cependant sûrement utile de pouvoir faire un screenshot après la réalisation de chaque action, spécifié ainsi : 
```
- name : 'page1'
  url: 'https://my-pages'
  # This screenshot is taken before running the actions !
  screenshot : 'output/screenshots/screenshot-page1.png'
  actions:
    - name: 'actions 1'
      type: 'click'
      element: 'a[id="action"]'
      timeoutBefore: 1000
      waitForSelector: 'span.popup'
      # This screenshot would be taken just after running the action
      screenshot : 'output/screenshots/screenshot-page1-action1.png'
```

**Comment by jpreisner** [comment]
Hello @PierreRustOrange, je me suis fait la réflexion récemment d'ajouter la possibilité de faire un screenshot par action. C'est une bonne idée. Je vois pour ajouter la fonctionnalité.
