### ISSUE TITLE
Pertinence de l’option --format

### ISSUE THREAD

**Issue by Krakor92** [cnumr/GreenIT-Analysis-cli#32]
Je m’interroge sur la pertinence de l’option `--format` pour la commande `analyse`.

Selon moi, il serait plus logique et intuitif d’écrire `./greenit analyse url.yml index.html`
plutôt que  `./greenit analyse url.yml index.html --format=html`

J’ai regardé son utilisation dans le code et elle sert uniquement dans le fichier `commands/analyse.js` pour savoir quel format de report créer. Mais c’est redondant avec l’extension du fichier que l'on doit écrire en argument du script.

---

Il suffit de remplacer le `if` ligne 73 dans le fichier `commands/analyse.js`
>`if(options.format === 'html') {`

par `if (path.extname(options.report_output_file) === '.html') {` pour ne plus avoir besoin d’utiliser l’option.

Y a-t-il une raison pour laquelle cette option existe que je ne comprends pas ?

**Comment by jpreisner** [comment]
Hello @Krakor92, effectivement on peut se poser la question de la pertinence de l'option `format` alors que l'extension du fichier de sortie pourrait suffire. Je l'avais ajouté pour une question de bonne lisibilité, mais c'est vrai qu'en l'état, ce n'est pas super utile. 

Si personne n'est contre, on peut donc supprimer l'option `format`.

**Comment by demeringo** [comment]
Hello all,

J'aime bien pouvoir passer un format explicite, il y a des cas (commen en CI) ou ca donne de la clarté et peux limiter les erreurs (en particulier si on passe le nom de fichier en variable, qui peut être configurée en dehors du script etc...).

Peut être qu'on pourrait avoir une option _optionnelle_, c'est à dire:

1. si l'option --format est passée, on utilise cette info
2. si rien n'est passé, on essaye de déduire le format à partir de l'extension du fichier (avec un petit message dans les logs ou la console type `No output format specified, defaulting to xxx based on output file name`.

**Comment by jpreisner** [comment]
Merci @demeringo pour ta proposition, c'est un très bon compromis et je partage ton point de vue :)
La PR a été créée !
