### ISSUE TITLE
Récupération du détail des analyses

### ISSUE THREAD

**Issue by ricardvince59** [cnumr/GreenIT-Analysis-cli#38]
Bonjour
Merci à tous pour le travail déjà réalisé.

J'aimerais savoir s'il est possible de récupérer dans les rapports le détail des analyses "en erreur" comme c'est le cas sur le plugin chrome (cf screenshoot)?

Pour être encore plus clair, dans le rapport excel, il y a le détail des images resize dans le navigateur, est-ce ce détail est généralisable dans les bonnes pratiques comme le nombre de domaine, les fichiers sans cache control,...?

Merci d'avance de votre aide

![screenGreenIssues](https://user-images.githubusercontent.com/87814778/167865939-e1377023-b9c2-4198-b6db-6cda1fbf9b99.png)

**Comment by jpreisner** [comment]
Salut @ricardvince59, ce n'est pas possible actuellement, mais ça serait intéressant d'ajouter cette fonctionnalité effectivement !

**Comment by MatisGalvin** [comment]
Salut @ricardvince59 ! Je t'apporte une piste, lorsque je lance une analyse avec greenit cli, un dossier results avec plusieurs fichiers au format JSON sont disponible 
![Capture](https://github.com/cnumr/GreenIT-Analysis-cli/assets/72927745/270e9f34-5e97-4e27-868f-cb0fdbb20d3b)

Ensuite, j'ai juste créé une page html avec un script js:
![Capture](https://github.com/cnumr/GreenIT-Analysis-cli/assets/72927745/e5990986-d185-4a66-9800-43c115856cb5)
Et avec ça, tu as les même résultats il me semble.

**Comment by jpreisner** [comment]
Hello @MatisGalvin,

Merci pour ton retour. J'avais oublié cette issue, mais je vais pouvoir la clore car nous avons rajouté la fonctionnalité depuis cette PR #62. Il est dorénavant possible d'avoir le détail d'une bonne pratique dans le rapport HTML.
