### ISSUE TITLE
Erreur build docker sur mac équipé d'une puce M1 

### ISSUE THREAD

**Issue by BenoitBBCorp** [cnumr/GreenIT-Analysis-cli#52]
Bonjour,

Il ne s'agit pas tout à fait d'une issue puisque j'ai la solution à mon pb, mais je souhaite la partager avec la communauté.

J'ai été confronté à 2 erreurs lors de la construction de l'image docker sur mon Mac M1.

1/ Soucis dans la commande de construction de l'image : il faut retirer la majuscule à imagename (vs imageName actuellement). Ce qui donne donc : `docker build -t imagename`

2/ J'obtenais ensuite une erreur au moment de la construction elle-même. J'ai contourné le problème en modifiant la première ligne du fichier docker de la manière suivante (en indiquant la nature du processeur) : 
`FROM --platform=linux/amd64 node:16-slim`
La construction s'est effectuée sans pb ensuite. 

J'espère que cela pourra être utile à d'autres.

**Comment by jpreisner** [comment]
Hello @BenoitBBCorp,

1/ Effectivement, on peut corriger le README pour éviter de tomber sur cette erreur. 

2/ As-tu tester de passer le paramètre `--platform=linux/amd64 node:16-slim` au niveau de la commande `docker build -t image-name .` ? Cela fonctionne-t-il ? Si oui, cette solution me semble préférable car cela éviterait de devoir modifier le Dockerfile. Et si cela fonctionne, nous pourrions le documenter dans le README :)

**Comment by BenoitBBCorp** [comment]
Cela fonctionne avec la commande `docker build --platform linux/amd64 -t imagename . ` !

**Comment by jpreisner** [comment]
@BenoitBBCorp : que penses-tu de cette proposition de PR pour compléter/corriger la doc ?
https://github.com/cnumr/GreenIT-Analysis-cli/pull/55
