### ISSUE TITLE
Impossible de run docker avec la commande proposée 

### ISSUE THREAD

**Issue by BenoitBBCorp** [cnumr/GreenIT-Analysis-cli#53]
La commande "docker run" actuellement indiquée ne semble pas être à jour (en tout cas ne fonctionne pas chez moi, toujours sur mon mac M1). Après plusieurs essais, j'arrive à une commande qui ne me retourne pas d'erreur mais qui ne fonctionne pas non plus : 
`docker run -it --init --rm imagename:latest -v /Users/bbarneoud/Documents/01 - ECO-CONCEPTION/DEPOT-CLI-GREENIT/input:/app/input -v /Users/bbarneoud/Documents/01 - ECO-CONCEPTION/DEPOT-CLI-GREENIT/output:/app/output -e TZ=Europe/Paris`

J'obtiens la réponse suivante (mais rien ne se passe) : 
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
v16.20.0`

Pour info, l'arbo du projet : 
- GreenIT-Analysis-cli (rep du projet)
- input (contient le fichier url.yaml)
- output

Merci d'avance pour votre aide !

**Comment by jpreisner** [comment]
Salut @BenoitBBCorp,

J'ai l'impression que c'est un problème qui a aussi un lien avec ton issue #52.

Malheureusement, je n'ai pas le matériel pour faire des tests de mon côté.

As-tu essayé de rajouter ceci, comme tu l'as fait d'ailleurs pour l'issue #52 : --platform=linux/amd64 ?

Exemple :

`docker run -it --init --rm imagename:latest -v /Users/bbarneoud/Documents/01 - ECO-CONCEPTION/DEPOT-CLI-GREENIT/input:/app/input -v /Users/bbarneoud/Documents/01 - ECO-CONCEPTION/DEPOT-CLI-GREENIT/output:/app/output -e TZ=Europe/Paris --platform=linux/amd64`

**Comment by BenoitBBCorp** [comment]
Bonjour @jpreisner,
J'ai un peu avancé en déplaçant l'ensemble du projet dans un nouveau répertoire : /Users/bbarneoud/greenitanalysis.

Lorsque je lance la commande `docker run -it --init --rm --cap-add=SYS_ADMIN -v /Users/bbarneoud/greenitanalysis/input:/app/input -v /Users/bbarneoud/greenitanalysis/output:/app/output -e TZ=Europe/Paris --name containerName imagename:latest` l'analyse se lance mais j'obtiens l'erreur suivante : 

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
No output format specified, defaulting to xlsx based on output file name.
 Analysing                [====         ] 33%     Remaining: 0.0s     Time: 0.0Error while analyzing URL https://bbcorp.fr/ :  Error: Protocol error (Target.createTarget): Target closed.
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:70:16)
    at Browser._createPageInContext (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:221:53)
    at BrowserContext.newPage (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:500:30)
    at Browser.newPage (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:214:37)
    at analyseURL (/app/cli-core/analysis.js:22:36)
    at createJsonReports (/app/cli-core/analysis.js:266:29)
    at analyse_core (/app/commands/analyse.js:75:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`
L'ajout de --platform=linux/amd64 en fin de commande ne change rien à l'affaire.

**Comment by BenoitBBCorp** [comment]
Voici mon yaml.url au cas où :
```
- name : 'bbcorp'
  url : 'https://bbcorp.fr/'
```
J'ai essayé avec plusieurs variations : avec et sans le 'name', les 'www', le index.html... cela ne change rien.

**Comment by jpreisner** [comment]
Je viens de tester chez moi en local, j'arrive bien à analyser ton site.

Voici le contenu de mon fichier `url.yaml` : 
```yaml
- name : 'bbcorp'
  url : 'https://bbcorp.fr/'
```

Voici la commande que j'ai joué en local (avec npm pour faciliter le debug) : 
`greenit analyse url.yaml result.html`

👉 Test 1 : Je doute que ça soit utile, mais essayons quand même : pourrais-tu ajouter dans le fichier `url.yaml` l'instruction permettant de prendre une capture d'écran du navigateur ? 

Ton fichier pourrait ressembler à ceci :
```yaml
- name : 'bbcorp'
  url : 'https://bbcorp.fr/'
  screenshot: 'output/screenshots/bbcorp.png'
```
👉 Test 2 : Je viens de merger une option qui pourrait t'être utile : la possibilité de désactiver le mode headless en local (lancement via npm et non via docker). Cela pourrait te permettre de voir ce qui se passe concrètement.

Exemple de commande : `greenit analyse url.yaml result.html --headless=false`

**Comment by BenoitBBCorp** [comment]
On arrive aux limites de mes compétences techniques... j'ai tenté de lancer la commande via npm de la manière suivante mais sans certitude qu'il s'agisse de la bonne manière de faire : `npm exec -c 'greenit analyse url.yaml result.html --headless=false'`. J'obtiens dans ce cas un "Permission denied" (comme lorsque je tente la commande sans le npm exec).

Pour info, lorsque j'essaie la méthode d'installation via Node.je, j'obtiens les erreurs suivantes lors de l'installation des dépendances (mais peut être que cela n'a pas de rapport) : 
```npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated puppeteer@5.5.0: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path /Users/bbarneoud/greenitanalysis/GreenIT-Analysis-cli/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64: 
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  apt-get install chromium-browser
npm ERR! 
npm ERR! /Users/bbarneoud/greenitanalysis/GreenIT-Analysis-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112
npm ERR!             throw new Error();
npm ERR!             ^
npm ERR! 
npm ERR! Error
npm ERR!     at /Users/bbarneoud/greenitanalysis/GreenIT-Analysis-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112:19
npm ERR!     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! 
npm ERR! Node.js v18.16.0
```

**Comment by jpreisner** [comment]
Est-ce que tu as pu essayé de faire un screenshot pour voir ce que ça donne ?

Et aussi, as-tu tenter d'analyse un autre site ?

Exemple : 
```yaml
- name : 'Collectif GreenIT.fr'
  url : 'https://collectif.greenit.fr/'
```

**Comment by BenoitBBCorp** [comment]
J'ai réussi (je ne sais trop comment) à faire tourner l'analyse directement via node (mais toujours pas via docker). Je vais m'arrêter là dans mes recherches car j'ai déjà passé beaucoup de temps et qu'au final, le fonctionnement via node est tout à fait satisfaisant ! Merci en tout cas pour l'aide.
