### ISSUE TITLE
Remplacer "Règles à corriger" par "bonnes pratiques à mettre en oeuvre"

### ISSUE THREAD

**Issue by bordage** [cnumr/GreenIT-Analysis-cli#59]
Remplacer "Règles à corriger" par "bonnes pratiques à mettre en oeuvre"

C'est important, pour que tout le monde  s'y retrouve de comprendre qu'on a  
1. une "bonne pratique d'écoconception" 
   dont nous testons la mise en oeuvre à l'aide de : 
   2. une "règle de test formel" ;
   3. un "seuil de conformité" quantifié.

**Comment by jpreisner** [comment]
Merci @bordage pour la suggestion d'amélioration. C'est corrigé :)
