### ISSUE TITLE
Output en InfluxDB : Erreur à l'export

### ISSUE THREAD

**Issue by vela-nova** [cnumr/GreenIT-Analysis-cli#78]
Lorsque je lance la commande pour exporter les reports en InfluxDB/Grafana, je tombe sur une erreur
```
ERROR : 
 Error: invalid integer value for field 'ecoindex': 'undefined'!
    at me.intField (/home/amin/Aepsilon/Repos/GreenIT-Analysis-cli/node_modules/@influxdata/influxdb-client/dist/index.js:4:2656)
    at /home/amin/Aepsilon/Repos/GreenIT-Analysis-cli/cli-core/influxdb.js:44:14
    at Array.map (<anonymous>)
    at write (/home/amin/Aepsilon/Repos/GreenIT-Analysis-cli/cli-core/influxdb.js:34:28)
    at analyse_core (/home/amin/Aepsilon/Repos/GreenIT-Analysis-cli/commands/analyse.js:87:15)
``` 
Apres avoir investigué l'erreur on dirait qu'elle est causée par la methode write du fichier influxdb.js qui tente d'acceder des attributs n'existant pas dans l'objet report (venant du JSON).

Je m'etonne aussi de ne pas voir le nom du scenario ou le nom de l'action dans les données envoyées a InfluxDB.

**Comment by jpreisner** [comment]
Salut @vela-nova,

Etonnant car ces attributs sont pourtant bien renseignés : 
- ecoindex : https://github.com/cnumr/GreenIT-Analysis-cli/blob/master/cli-core/influxdb.js#L54
- scenarioName : https://github.com/cnumr/GreenIT-Analysis-cli/blob/master/cli-core/influxdb.js#L47
- actionName : https://github.com/cnumr/GreenIT-Analysis-cli/blob/master/cli-core/influxdb.js#L50

Est-ce que tu t'es bien mis à jour par rapport aux dernières évolutions ?

N'hésite pas à partager la façon dont tu utilises l'outil (npm ou docker ? quelle commande tu utilises pour le build ? pour le lancement de l'analyse ? etc...) de façon à ce qu'on puisse reproduire en local

**Comment by vela-nova** [comment]
Salut,
Je m'excuse de la fausse alarme. 

Apres avoir replongé le sujet j'ai remarqué que le dernier commit que j'avais pull quand j'avais crée cette issue etait le commit https://github.com/cnumr/GreenIT-Analysis-cli/commit/f5cd96dd42c044c4248b17d36a748e8d232456c7 et il se trouve qu'entre temps la partie InfluxDB/Grafana avait eu des développements. 

Lorsque j'ai essayé d'utiliser l'export en InfluxDB/Grafana avec les derniers changements j'ai eu 0 soucis.

Je ferme donc cette issue.
Merci beaucoup.
